#!/bin/sh
CP1=../../BUILD/scrunner.jar:../../BUILD/lsnof.jar:../../BUILD/yrunner.jar
CP=$CP1:../../BUILD/sbl.jar
java -classpath $CP -Djava.security.policy=../../BUILD/libbzdev.policy \
       org.bzdev.bin.scrunner.SCRunnerCmd "$@"
