.TH SBL "5" "Nov 2014" "sbl VERSION" "File Formats and Conventions"
.SH NAME
sbl \- sbl input file
.SH DESCRIPTION
.PP
.B SBL
(Secure Basic Launcher) configuration files are stylized Java property
files using the UTF-8 character set with an end of line indicated by
a carriage return followed by a line feed.  While the file name extension is
.BR sbl ,
the file type can be determined by their first line:
.br
.sp
#(!m.T\ application/vnd.bzdev.sblauncher)
.br
.sp
which encodes the file's media type (MIME type).  The remainder of the
file contains a key given as a qualified name, followed by an "=", and
finally followed by a value.  If the key starts with "base64", the
value is URL-safe base-64 encoded with no line breaks.  Similarly
if the key starts with "ebase64", the value is encrypted with GPG
and then encoded using the URL-safe base-64 encoding.
.PP
There are several reserved keys (property names):
.TP
.B recipients
A base-64 encoded value That consists of the GPG key IDs used to
encrypt the values of
.B ebase64
keys, with each pair of GPG key IDs separated by a NEWLINE character.
.TP
.B title
A user-specified title to display for this file.
.TP
.B base64.keypair.publicKey
The public key.
.TP
.B ebase64.keypair.privateKey
The GPG-encrypted private key
.TP
.B trustStore.file
The file name for an additional trust store to use in addition to the
Java "cacerts" default.  A trust store contains self-signed
certificates that are deemed to be trusted for signing other
certificates. This entry is useful for software testing.
.TP
.B ebase64.trustStore.password
The password for the trust store file.
.TP
.B trust.selfsigned
The value is
.B true
if a self-signed server's certificate can be automatically accepted;
.B false
otherwise.
.TP
.B trust.allow.loopback
The value is
.B true
if the server can be found on the loopback interface;
.B false
otherwise. This option was provided mainly for stand-alone testing.
.PP
The remaining keys are partially user-specified.  For each name
.I NAME
that user chooses, the corresponding keys are
.TP
.B \fINAME\fB.description
The value is a textual description for this entry.
.TP
.B \fINAME\fB.mode
The value is the type of the passphrase generated
.BR \fR(\fBDIGEST ,
.BR PASSWORD_WITHOUT_CERT ,
.BR PASSWORD_WITH_CERT ,
.BR PASSWORD ).
.TP
.B ebase64.\fINAME\fB.password
The value is the user-supplied password, which is automatically provided
when
.BR sbl \'s
add-entry option is used. In an SBL file, these values are encoded
as the integers 0, 1, 2, or 3 respectively.
.TP
.B \fINAME\fB.base
The value is the URI used to find a protected part of a web site,
a URL that represents a directory or some similar URL/URI path component.
It should end with the character
.BR /,
which
.B sbl
will append if necessary when its "add entry" function is used to
set up a new entry.
.TP
.B \fINAME\fB.uri
The value is the URI used to find a web site. It should start with
the value of
.BR \fINAME\fB.base :
when generating this field, the program
.B sbl
will ask the user for a relative path and query, and that will be
appended to the string
.BR $(\fINAME\fB.base)\  ,
which is expanded to the value of corresponding to the key
\fINAME\fB.base\fR, when
.BR sbl \'s
"add entry" function is used to set up a new entry.
.TP
.B \fINAME\fB.user
The value is the user's login name for this web site.
.SH SUBSTITUTION
.PP
For keys that do not start with
.B base64
or
.BR ebase64 ,
when a value contains
.BI $( KEY )
that expression will be replaced with the value corresponding
to
.IR KEY .
The escape sequence
.B $$
is treated as a single
.BR $ .
Substitutions are not performed when an SBL file is being edited by
the program
.BR sbl .
.SH JSON
When a  JSON object is produced by
.BR sbl ,
the object will be printed to standard output is a JSON object with
two name-value pairs with the following keys:
.TP
.B serverInfo
The value is a JSON object
.TP
.B clientInfo
The value is an SBL file that is Base-64 encoded and contains the fields
used by a client.
.TP
For the
.B serverInfo
key, the value is a JSON object with the following keys:
.TP
.B title
A title for this object
.TP
.B base64.keypair.publicKey
The base-64 encoded public key for a user. The decoded value specifies
a signature algorithm and a PEM-encoded public key.
.TP
.B \fINAME\fB.user
A user name, where
.I NAME
is an identifier specifying a group of entries.
.TP
.B base64.\fINAME\fB.password
is a password, base64 encoded, where
.I NAME
is an identifier specifying a group of entries.
.TP
.B \fINAME\fB.base
The base URI, where
.I NAME
is an identifier specifying a group of entries.
.TP
.B \fINAME\fB.description
The description for this server + base, where
.I NAME
is an identifier specifying a group of entries.
.TP
.B \fINAME\fB.mode
The mode as an integer (this will frequently be "2" indicating the
enumeration constant
.B SIGNATURE_WITH_CERT
defined by the enumeration
.BR SecureBasicUtilities.Mode ),
where
.I NAME
is an identifier specifying a group of entries.
.SH SBL FILES FROM SERVERS
.PP
When an SBL file is provided by a server, it will contain two
additional fields
.TP
.B sbl.downloaded
This field will have the value
.B true
indicating that the file was download from a server, will generally
not be modified, and that SBL can use a simplified user interface.
.TP
.B ebase64.user.digest
This field contains a Base-64 encoded SHA-256 message digest covering
the PEM formated private key (including the signature algoritm), the
password, the mode (as a small integer as described above), the user
name, the base URI, and the URI to visit when logging in. The digest
is encrypted using GPG or PGP.  Since the digest covers fields that a
third party cannot read, a "man in the middle" cannot alter the fields
in an SBL file used to estabilish a connection and authorize a user
without the alteration being detected.
.PP
When an account is being created, one can request data from the server,
and that data will be returned as an SBL file.  In this case, the
fields in this SBL file are
.TP
.B mode
The values are described above.
.TP
.B sbl.downloaded
When present, the value will always be
.BR true .
.TP
.B need
The value is either
.BR pgpkey ,
in which case a GPG key should be uploaded or
.BR sbl ,
in which case an SBL file providing the user name, password, and
public key should be uploaded.
.TP
.B recipients
This field lists the recipients that can decrypt a GPG encrypted value.
.TP
.B user
This field provides the user name
.TP
.B base
This provides the 'base' URL - basically the common portion of URLs
that should be authenticated
.TP
.B loginAlias
This field provides the remainder of a path to add to the base to
indicate the URL to use to log in or set up an account.
(a '/' will be automatically added to the base URL if the base URL
does not end in a '/').
.PP
Fields such as
.BR trust.allow.loobpack ,
.BR trust.selfsigned ,
.BR trustStore.file ,
and/or
.BR ebase64.trustStore.password
may also be present, primarily during testing, and a digest field
is not provided.
.SH SEE ALSO
.PP
.BR sbl (1)

\"  LocalWords:  SBL sbl UTF br sp ebase GPG TP trustStore selfsigned
\"  LocalWords:  loopback fINAME fB fI fBDIGEST uri fR
