.TH SBL "1" "June 2023" "libbzdev-util VERSION" "User Commands"
.SH NAME
sbl \- create passphrases for use with secure basic authentication
.SH SYNOPSIS
.B sbl
.br
.B sbl\ \fICFILE
.br
.B sbl \fB[\fIOPTION\fB]...\fR \fICFILE\fB
.B sbl\ \=\-create\ ]\fIOPTION\fB]...\ [\fICFILE1\ CFILE2\fB]
.SH DESCRIPTION
.PP
The program
.B sbl
(Secure Basic Launcher) provides a simple graphical user interface
for web sites that use Secure Basic authentication. Secure Basic
authentication differs from Basic authentication in that the
password is replaced with a passphrase that is a digital signature.
Once verified, this passphrase can be used like a traditional
password.  It is intended to be secure when used with TLS/SSL,
in which case the passphrase consists of a time stamp, a 32-bit
CRC of the time stamp and a traditional password, and a digital
signature of the time stamp, the CRC, the SSL certificate's
public key, and the password.  Once verified, this signature is
treated as a basic-authentication password, accepted provided the
sender's IP address has not changed.
.PP
Configurations are stored in files typically with the
file-name extension
.BR sbl .
Each file will typically include sites, or logins, that are related in
some way (the grouping is chosen by each user). There is one
special case: if a configuration file contains a single site or login,
and the configuration file is provided on the command line, that site or
login will be selected.  Web sites can provide an
.B sbl
configuration file and browsers can start
.B sbl
for the user.  The special case allows the user to skip the step of
selecting a site, and can simply click the
.B Open\ Browser
button, and then paste the user name and password.
.PP
While there are
some command-line options for specific tasks, typically
.B sbl
will be used to open a browser window for a specific URI by
clicking the
.B Open\ Browser
button, and simultaneously a user name and a a secure basic
authentication passphrase will be copied to the system clipboard,
which can then be pasted into a dialog box or text field provided by a
browser.  Pasting in this case is handled specially: pasting alternates
between pasting the user name and pasting the passphrase. The browser
will typically pop up a dialog box asking for a user name and password,
so the user can click on the user-name field, and paste a value from
the clipboard, and then click on the passphrase/paswword field and paste
from the clipboard again.
.PP
When
.B sbl
is run with no arguments, or one argument (an
.B sbl
configuration file
.IR CFILE )
with no options except
.BR \-\-,
it will provide a window with a series of buttons or controls for
specific operations.  These are
.TP
.B Load
A new configuration file will be loaded. A "file chooser" dialog box
will allow a configuration file to be selected. If a file name that
does not exist is entered, a new file will be created.
.TP
.B Select\ Site
This will allow one to select a web page to visit, based on an
identifier providing a short name for the page.
.TP
.B Open\ Browser
This will open a window using the user's default browser. It will also
generate a passphrase, and will copy both the user name and the
corresponding passphrase to the system clipboard so both can be
pasted into the appropriate text fields displayed by a browser. Pasting
is handled specially: each time the copy is pasted the value provided
alternates between the user name and the passphrase, starting with the
user name.
.TP
.B Generate\ Passphrase
This will generate a new passphrase for the selected site.
.TP
.B Add\ Entry
This will add a new entry the configuration file's tables.
.TP
.B Edit\ Entries
This will allow the user to edit the configuration file.
.TP
.B Copy\ User\ Name
This will copy the user name for the selected site to the
system clipboard.
.TP
.B Copy\ Public\ Key
This will copy the public key for the selected site to the
system clipboard.
.TP
.B Copy\ Password
This will copy the user's password for the selected site to the
clipboard.  For secure basic authentication, a traditional password
is used for two purposes: (1) to quickly reject bad authentication
requests, and (2) so that passwords can differ when two web sites
share the same certificate (web sites that are part of a larger
organization sometimes share certificates).
.PP
When the SBL file is explicitly provided on the command line, a
leading directory name of
.B ...
will be replaced with the default SBL directory.  On a Linux or Unix
system, for example,
.B .../example.sbl
would be replaced with
.BR ~/.config/sbl/example.sbl\  (
the directory
.B ~/.config/sbl
is the directory the
.B Load
button's open-file dialog uses.

.SH OPTIONS
The options are
.TP
.B \-\-
Terminate options.
.TP
.BI \-\-base\  BASE_URI
This option, used only with the
.B \-\-create
option, provides a base URI representing a portion of a website or server
that is protected by an SBL-compatable authenticator.
.TP
.B \-c
.TQ
.B \-\-create
Create a new SBL file. If the arguments
.I CFILE1
and
.I CFILE2
are present after the options, that will specify the name of
the files to create. If one of these is "-", its output will be
directed to standard output.  In all cases,
.I CFILE1
will contain the entries needed by a server and
.I CFILE2
will contain the entries needed by a client.
If the arguments
.I CFILE1
and
.I CFILE2
are not provided, the file will be printed to standard output as
A JSON object (see the man page
.BR sbl (5)).  When the
.B \-\-create
option is used, Several options are mandatory:
.BR \-\-base ,
.BR \-n ,
.BR
.BR \-\-uri ,
and
.BR \-\-user .
The optional options for
.B \-\-create
are
.BR \-\-loopback ,
.BR \-\-selfSigned ,
.BR \-\-truststore ,
and
.BR  \-\-truststorePW .
.TP
.BI \-\-gpgdir\  DIRECTORY
Use
.I DIRECTORY
as the GPG home directory. The option is useful when a server maintains
its own GPG key ring.
.TP
.B \-f
Suppress a dialog box that asks permission to use a trust store,
loopback host name, or a self-signed certificate. This dialog box
mill otherwise appear if an
.B sbl
file is provided as a command-line argument.
.TP
.B \-\-loopback
This option, used only with the
.B \-\-create
option, indicates that the loopback address denotes a valid host.
.TP
.BI \-n\  NAME
This option sets the identifier used to reference a particular
entry in an SBL file that was passed to
.B sbl
as its only non-option argument. In this case, the argument
.I NAME
is the identifier that will be displayed by the
.B Select\ Site
box.
.I NAME is also used with the
.B \-\-create
option to set the key for an entry - the identifier that will appear as
part of a property key.  For the
.B \-\-create
option, a missing
.B \-n
option will result in an entry with the default key
.BR user.
.TP
.B \-\-print\ \fIPOPTION\fB
The argument
.I POPTION
can be
.B user
(to print the user name to use when logging into the web site),
.B uri
(to print the URI for the web page),
.B description
(to print the description of the web page),
.B password
(to print the user-supplied password),
.B mode
(to print the type of authentication used),
.B publicKey
(to print the public key for this configuration file),
.B list
(to print a list of the identifiers used to select a web page.)
.PP
For the
.B \-\-print
option, except when its argument
.I POPTION
is
.BR list ,
a
.B \-n
option will also be needed.
.TP
.B \-\-selfSigned
This option, used only with the
.B \-\0 create
option, indicates that a client should accept self-signed
certificates. This option should be used only for testing.
.TP
.B \-\-stacktrace
This option configures
.B sbl
so that it prints a stack trace if an exception that terminates
the program is thrown.
.TP
.BI \-\-truststore\  FILE
This option, used only with the
.B \-\-truststore
option, provides the name of a file containing a trust store.
.TP
.BI \-\-truststorePW\  PASSWORD
This option, used only with the
.B \-\-create
option, provides the trust-store password
.IR PASSWORD .
.TP
.BI \-\-uri\  URI
This option, used only with the
.B \-\-create
option, provides the URI that should be visited when a user first
logs in.

.TP
.BI \-\-user\  NAME
This option provide a user name,
.BR NAME ,
used for a web site or server's login.
.TP
.BI \-r\  GPGKEY
The argument
.I GPGKEY
is any valid GPG user ID that will name a key in the user's key ring,
and multiple
.B \-r
options are allowed. When at least one
.B \-r
option is present, private keys will be encrypted using all of these
user IDs to determine which users can decrypt a private key.  If
a configuration file is provided on the command line, the key pair
for that file will be replaced and
.B sbl
will exit. If no configuration file is provided or a specified key
file does not exist, then when a new
configuration file is created, the private key will be encrypted so
that the users specified by the
.B \-r
options can decrypt it.
.SH FILES
.I ~/.config/sbl
This directory contains configuration files. Each will have
its own key pair, and will otherwise list web sites, user names,
and their corresponding passwords.
.SH SEE ALSO
.BR sbl (5)

\"  LocalWords:  fIOPTION fICLASSNAME fR subclasses CLASSNAME javadoc
\"  LocalWords:  NamedObjectFactory codebase classname superclass TP
\"  LocalWords:  getTemplateKeyMap BZDev URLPATH dryrun JOPTION TQ br
\"  LocalWords:  stackTrace baseURL subdirectories DIRNAME api html
\"  LocalWords:  toplevel factoryDoc charset CHARSET UTF templateURL
\"  LocalWords:  templateResource templateFile definingClass bzdev fI
\"  LocalWords:  definingClassHTML RESOURCENAME listCodeBase rdanim
\"  LocalWords:  subdirectory roadanim scrunner fRor Solaris config
\"  LocalWords:  conf SBL libbzdev util sbl fICFILE fB CFILE POPTION
\"  LocalWords:  fIPOPTION uri publicKey TLS SSL CRC loopback
