PEM = PEM encoding not readable
positiveLowerTDL = The lower time-difference limit is positive: %d
negativeUpperTDL = The upper time-difference limit is negative: %d
passphraseTimeout = Passphrase timeout %d < upper time-difference limit %d

negativePassphraseTimeout = Passphrase timeout must not be negative: found %d

wrongMode = the current method does not support the mode "%s"
certlength = Certificate chains not compatible


# LocalWords:  PEM positiveLowerTDL negativeUpperTDL passwordTimeout
