wrongMode = An 'add' method is not consistent with the mode %s
authTwoServers = Attemped to add an authenticator to two servers
authPrefix = Tried to add "%s" but "%s" already added
noPrefix = Prefix not available

PEM = PEM encoding not readable
positiveLowerTDL = The lower time-difference limit is positive: %d
negativeUpperTDL = The upper time-difference limit is negative: %d
passphraseTimeout = Passphrase timeout %d < upper time-difference limit %d

negativePassphraseTimeout = Passphrase timeout must not be negative: found %d

wrongMode = the current method does not support the mode "%s"
certlength = Certificate chains not compatible

hasUser = User "%s" already added
description = %s login

certError =  Certificate not an X509 certificate
frozen = Operation failed because the configuration is now frozen
wrongAddUser = the wrong addUser method was called
noSBL = not allowed: will not create SBL File
badRecipient = Unknown or ill-formed recipient: %s
duplicateRecipient =  Duplicate recipient: %s
badRecipientFetch = Recipient lookup failed: %s
badPropsFile = Property file does not have a KEY.description entry

badGPGKey = Ill-formed GPG key or some other GPG error
keyConflict = Existing GPG key for %s (different fingerprints)?
missingEmail = Email address missing in GPG key %s
ambiguousEmail = GPG email search for "%s" found the wrong key
trustUpdate = GPG could not update trust for %s
illformedEmail - An email address was illformed: %s

noGPGHome = No GPG home directory specified - was null
sbldir = Not a directory: %s

noSBLDir = No SBL directory specified - was null
noSBLStore = No SBL store specified - was null

pleaseVisit = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Please visit the login page<BR>%s</BODY></HTML>

badPasswords = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Passwords did not match. Please try again</BODY></HTML>

badPWSetup = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Password Setup</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Passwords and/or user name missing. Expecting form<br>\
	data with field names user, pw1, and pw2.</BODY></HTML>

badAccountCreation = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request Failed</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Cannot add an account: URI = %s</BODY>\
	</HTML>

noAccountCreation = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request Failed</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Cannot add accounts</BODY>\
	</HTML>

accountExists = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request Failed</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Account for "%s" already exists</BODY>\
	</HTML>

noUserAccount = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request Failed</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>No account for "%s"</BODY>\
	</HTML>

useSBL =  <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request Failed</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Use the SBL application to log in as "%s"</BODY>\
	</HTML>


noDelete =  <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Delete Request Failed</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Cannot delete account "%s"</BODY>\
	</HTML>

processingAC =  <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Account Setup</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Account creation being processed:<br>\
	When done, please visit URI = %s</BODY>\
	</HTML>

pending = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Account Pending</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Account creation for %s is pending.</BODY>\
	</HTML>

pending0 = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Account Pending</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Account creation is pending.<BR>\
	<A HREF="%s">Continue.</A></BODY></HTML>

loginTimedout = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Account Pending</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Login has timed out.<BR>\
	<A HREF="%s">Continue.</A></BODY>\
	</HTML>

loginLocation =  <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Account Pending</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}</STYLE>\
	</HEAD><BODY>Please use the login page.<BR>\
	<A HREF="%s">Continue.</A></BODY>\
	</HTML>

setPassword = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Set Password</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}\
	TD {padding-top: 5px; padding-bottom: 5px;}</STYLE> \
	</HEAD><BODY><H1>Set password for %1$s</H1> \
	<FORM ACTION="%2$s" METHOD="POST" \
	      enctype="application/x-www-form-urlencoded">\
	<INPUT type="hidden" name="user" value="%1$s">\
	<TABLE>\
	<COL ALIGN="RIGHT"><COL ALIGN=LEFT>\
	<TR><TH>Password:<TD><INPUT type="password" name="pw1" size="40">\
	<TR><TH> <TD> \
	<TR><TH>Reenter PW:<TD><INPUT type="password" name="pw2" size="40">\
	</TABLE><BR><BR><INPUT type="submit" VALUE="SUBMIT">\
	</FORM></BODY></HTML>

setPasswordAuth = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Set Password</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	<STYLE TYPE="text/css">BODY {background-color: rgb(10,10,25);\
	color: rgb(255,255,255);}\
	TD {padding-top: 5px; padding-bottom: 5px;}</STYLE> \
	</HEAD><BODY><H1>Set password for %1$s</H1> \
	<FORM ACTION="%2$s" METHOD="POST" \
	      enctype="application/x-www-form-urlencoded">\
	<INPUT type="hidden" name="user" value="%1$s">\
	<INPUT type="hidden" name="authcode" value="%3$s">\
	<TABLE>\
	<COL ALIGN="RIGHT"><COL ALIGN=LEFT>\
	<TR><TH>Password:<TD><INPUT type="password" name="pw1" size="40">\
	<TR><TH> <TD> \
	<TR><TH>Reenter PW:<TD><INPUT type="password" name="pw2" size="40">\
	</TABLE><BR><BR><INPUT type="submit" VALUE="SUBMIT">\
	</FORM></BODY></HTML>

Response409 = 409 server response

missingUserName = User name is missing from SBL file
noDirs = Neither the GPG Home directory nor the SBL directory were set

noScheme = The URI did not include a scheme
notHttps = The scheme was not HTTPS
noHost = the URI did not include a host
noPort = the URI did not include a port and there is no default
noChain = a certificate chain could not be obtained



# LocalWords:  PEM positiveLowerTDL negativeUpperTDL passwordTimeout
