wrongMode = An 'add' method is not consistent with the mode %s
authTwoServers = Attemped to add an authenticator to two servers
authPrefix = Tried to add "%s" but "%s" already added

PEM = PEM encoding not readable
positiveLowerTDL = The lower time-difference limit is positive: %d
negativeUpperTDL = The upper time-difference limit is negative: %d
passphraseTimeout = Passphrase timeout %d < upper time-difference limit %d

negativePassphraseTimeout = Passphrase timeout must not be negative: found %d

wrongMode = the current method does not support the mode "%s"
certlength = Certificate chains not compatible

hasUser = User "%s" already added
description = %s login

certError =  Certificate not an X509 certificate
frozen = Operation failed because the configuration is now frozen
wrongAddUser = the wrong addUser method was called
noSBL = not allowed: will not create SBL File
badRecipient = Unknown or ill-formed recipient: %s
duplicateRecipient =  Duplicate recipient: %s
badRecipientFetch = Recipient lookup failed: %s
badPropsFile = Property file does not have a KEY.description entry

badGPGKey = Ill-formed GPG key or some other GPG error
keyConflict = Existing GPG key for %s (different fingerprints)?
missingEmail = Email address missing in GPG key %s
ambiguousEmail = GPG email search for "%s" found the wrong key
trustUpdate = GPG could not update trust for %s

noGPGHome = "no GPG home directory specified - was null"

pleaseVisit = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	</HEAD><BODY>Please Visit <A HREF="%s">the login page</A></BODY>\
	</HTML>

# LocalWords:  PEM positiveLowerTDL negativeUpperTDL passwordTimeout
