title0 = SBL
title = SLB - %s
loadButton = Load
loaded = Loaded
site = Site
selectSiteCB = Select Site
visitSiteButton = Open Browser
generateButton = Generate Passphrase
addEntryButton =  Add Entry
editEntriesButton = Edit Entries
copyUserButton = Copy User Name
copyPWButton = Copy Password
copyPubKeyButton = Copy Public Key


errorTitle = SLB Error
configTitle = SBL Configuration
extensionFilterTitle = SBL Files

description = Description
base = Base URI
uri = Relative Path & Query
user = User
# password = Password
mode = Mode

name = Enter a name for a new entry
nameTitle = New Entry Name
entryTitle = Entry for "%s"
badName = Illegal name (must have Java-identifier syntax): %s

encryptFailed = GPG encryption failed (bad recipient?): try again?
encryptFailedTitle = GPG Encryption Error

printerr = print option not allowed (%s)
noConfigFile = no configuration file provided
existingConfigFile = the configuration file already exists ("%s")
multiplePrints = multiple --print options
noName = -n option missing
badOption = unrecognized option (%s)
missingArg = argument to "%s" option missing
rlistEmpty = no GPG recipients provided (add a -r option)
noUser = --user option missing
noURI = --uri option missing
noBASE = --base option missing

DIGEST = DIGEST
PASSWORD = PASSWORD
SIGNATURE_WITH_CERT = SIGNATURE WITH CERTIFICATE
SIGNATURE_WITHOUT_CERT = SIGNATURE WITHOUT CERTIFICATE

aPublicKey = public key
ffdescr = Trust-Store Files
recipients = recipients

File = File
Close = Close
VK_FILE = VK_F
Open = Open (Load)
Find = Select
Browser Open Browser

REQ = <html>Requested<UL><LI>trust store = %s \
    <LI>self signed = %b \
    <LI>loopback allowed = %b </UL></html>
REQTITLE = SBL Configuration

acceptSelfSigned = Accept a self-signed certificate?
acceptSelfSignedTitle = SBL Certificate Question

openConsole = Open Console
console = SBL Console
noCertificate = No certificate
nocert = No Certificate for host %s, port %d

headless = a display, keyboard, or mouse is not available

noScheme =  URI scheme missing
noHost = URI host field missing
unsupportedScheme = Scheme %s not supported
noPassword = No password: %s
