title0 = SBL
title = SLB - %s
titleText = upload PGP/GPG key to %s
titleText1 = Login to %s with PGP/GPG key
titleText2 = Create SBL file for %s
titleText3 = SBL - Operation complete
loadButton = Load
loaded = Loaded
site = Site
selectSiteCB = Select Site
visitSiteButton = Open Browser
generateButton = Generate Passphrase
addEntryButton =  Add Entry
editEntriesButton = Edit Entries
copyUserButton = Copy User Name
copyPWButton = Copy Password
copyPubKeyButton = Copy Public Key

foundKeys = <html>Found %d GPG/PGP public keys:<BR>cannot upload</html>
foundKey = <html>Found public key for %s:<BR>fingerprint = %s</html>
nonEmailLogin = <html> Logging in for user "%s": no GPG key available</html>
OK = OK
CANCEL = CANCEL
COPY = COPY User & PW
LOGIN = LOGIN
EXIT = EXIT
pwGenFailed = Failed to create an SBL password/passphrase
userConflict = SBL file contains user "%s" but "%s" specified

loginFor = <html>Creating login for %s,<br>Site: %s</html>

loginForDesc = login for %s


errorTitle = SLB Error
configTitle = SBL Configuration
extensionFilterTitle = SBL Files
canNotSave = File "%s" could not be saved
fileExists = File "%s" exists
notHTTP = Not HTTP or HTTPS
badURI = Syntax error for URI %s
contentType = Cannot process content type %s

hintTitle = SBL Hint
init3Hint = <html>Optionally edit to review <BR>\
	          or make changes; use the <BR>\
		  "Send login data" File <BR>
		  menu item to set up a login</html>

rcodeTitle = Upload status
sblSuccess = Account created (response code = %d)
sblFailed = <html>Account creation failed or state unknown<br> \
	  (response code = %d)</html>
sblFailed2 = <html>Account creation failed or state unknown<br> \
	   (response code = %d): %s</html>

description = Description
base = Base URI
uri = Relative Path & Query
user = User
# password = Password
mode = Mode

name = Enter a name for a new entry
nameTitle = New Entry Name
entryTitle = Entry for "%s"
badName = Illegal name (must have Java-identifier syntax): %s

encryptFailed = GPG encryption failed (bad recipient?): try again?
encryptFailedTitle = GPG Encryption Error

printerr = print option not allowed (%s)
noConfigFile = no configuration file provided
existingConfigFile = The configuration file already exists ("%s")
duplicateStdout = Two command-line arguments denote standard output
multiplePrints = multiple --print options
noName = -n option missing
badOption = unrecognized option (%s)
missingArg = argument to "%s" option missing
rlistEmpty = no GPG recipients provided (add a -r option)
noUser = --user option missing
noURI = --uri option missing
noBASE = --base option missing

DIGEST = DIGEST
PASSWORD = PASSWORD
SIGNATURE_WITH_CERT = SIGNATURE WITH CERTIFICATE
SIGNATURE_WITHOUT_CERT = SIGNATURE WITHOUT CERTIFICATE

aPublicKey = public key
ffdescr = Trust-Store Files
recipients = recipients

File = File
Close = Close
VK_FILE = VK_F
Open = Open (Load)
Find = Select
Browser Open Browser
gpgPublicKey = Copy GPG Key to Clipboard
gpgFailed1 = GPG failed to get public key IDs
gpgFailed2 = GPG failed to get public key
GPGKeyID = Select GPG key ID:
GPGKeyIDTitle = GPG Key ID

serverSBL = Copy Server SBL to Clipboard
serverSBL2 = Send SBL data to server

REQ = <html>Requested<UL><LI>trust store = %s \
    <LI>self signed = %b \
    <LI>loopback allowed = %b </UL></html>
REQTITLE = SBL Configuration

acceptSelfSigned = Accept a self-signed certificate?
acceptSelfSignedTitle = SBL Certificate Question

openConsole = Open Console
console = SBL Console
noCertificate = No certificate
nocert = No Certificate for host %s, port %d

headless = a display, keyboard, or mouse is not available

noScheme =  URI scheme missing
noHost = URI host field missing
unsupportedScheme = Scheme %s not supported
noPassword = No password: %s
noPrivateKey = No private key
noPasswordAvailable = Password not available

pgpCnflct = <html>PGP key named "%s" <br>already used by server</html>
sblCnflct = <html>SBL data for "%s" <br>\
	    already in use or data ill-formed</html>
status = HTTP response status code = %d

pleaseVisit = <!DOCTYPE HTML><html lang="en">\
	<HEAD><title>Login Request</title>\
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\
	</HEAD><BODY>Please Visit <A HREF="%s">the login page</A></BODY>\
	</HTML>

noRecipients = [no recipients]
standardTitle = SBL configurations - %s

digestMsg = File from server modified in transit
digestTitle = Security Issue
